EnsemblIDFilter <- function(ExcelDataFilePath, BioMartExportFilePaths = NA, PassedEnsemblIDArray = NA, ExcelDataFileEnsemblIDColumnName = "ensembl_gene_id", BioMartExportEnsemblIDColumnName = "Turquoise.killifish.gene.stable.ID", ReAdjustPValues = TRUE, PValueColumnName = "pvalue", AdjustedPValueColumnName = "padj") {
  
  suppressPackageStartupMessages(library("readxl"))
  
  # Optional: gather all Ensembl IDs that passed the filtering (overrides PassedEnsemblIDArray if BioMartExportFilePaths != NA)
  if (!is.na(BioMartExportFilePaths)) {
    PassedEnsemblIDArray <- c()
    for (i in 1 : length(BioMartExportFilePaths)) {
      CurrentBioMartTable <- read.table(BioMartExportFilePaths[i], header = TRUE, sep = "\t")
      PassedEnsemblIDArray <- c(PassedEnsemblIDArray, CurrentBioMartTable[, BioMartExportEnsemblIDColumnName])
    }
    PassedEnsemblIDArray <- unique(PassedEnsemblIDArray)
  }
  
  # Filtering
  Data <- read_excel(ExcelDataFilePath)
  isRetained <- logical(nrow(Data)) # initialize an array of FALSEs
  for (i in 1 : nrow(Data)) {
    if (Data[i, ExcelDataFileEnsemblIDColumnName] %in% PassedEnsemblIDArray) {
      isRetained[i] <- TRUE
    }
  }
  FilteredData <- Data[isRetained,]
  
  # Readjust p-values if required
  if (ReAdjustPValues) {
    # Sort the table by p-values: unnecessary if the Excel data file was generated by the Flaski RNAseq pipeline (because the genes were sorted by their p-values already)
    
    # Re-adjust p-values using the Benjamini--Hochberg correction (do not adjust p = NA; return 1 if the calculated p-adj > 1; preserve the order)
    # Method 1:
    # for (i in nrow(FilteredData) : 1) {
    #   FilteredData[i, AdjustedPValueColumnName] <- min(FilteredData[i, PValueColumnName] * sum(!is.na(FilteredData[, PValueColumnName])) / i, 1)
    #   if (!is.na(FilteredData[i + 1, AdjustedPValueColumnName]) &
    #       (FilteredData[i + 1, AdjustedPValueColumnName] < FilteredData[i, AdjustedPValueColumnName])) {
    #     FilteredData[i, AdjustedPValueColumnName] <- FilteredData[i + 1, AdjustedPValueColumnName]
    #   }
    # }
    # Method 2 (using the built-in function p.adjust()):
    FilteredData[, AdjustedPValueColumnName] <- p.adjust(unlist(FilteredData[, PValueColumnName]), method = "fdr")
  }
  
  return(FilteredData)
}
