GOFilter <- function(ExcelDataFilePath, GOList, GOTermColumnName = "GO_id", ReAdjustPValues = T, PValueColumnName = "pvalue", AdjustedPValueColumnName = "padj") {
  suppressPackageStartupMessages(library("readxl"))
  
  # Filtering
  Data <- read_excel(ExcelDataFilePath)
  ChildNodeIDs <- get_unique_child_nodes_batch(GOList, godir = NULL)
  isRetained = logical(length = nrow(Data)) # initialize an array of FALSEs
  for (i in 1 : nrow(Data)) {
    if (length(intersect(convert_string_to_go_array(Data[i, GOTermColumnName]), ChildNodeIDs)) != 0) {
      isRetained[i] <- TRUE
    }
  }
  FilteredData <- Data[isRetained,]
  
  # Readjust p-values if required
  if (ReAdjustPValues) {
    # Sort the table by p-values: unnecessary if the Excel data file was generated by the Flaski RNAseq pipeline (because the genes were sorted by their p-values already)
    
    # Re-adjust p-values using the Benjamini--Hochberg correction (do not adjust p = NA; return 1 if the calculated p-adj > 1)
    # Method 1:
    for (i in 1 : nrow(FilteredData)) {
      FilteredData[i, AdjustedPValueColumnName] <- min(FilteredData[i, PValueColumnName] * sum(!is.na(FilteredData[, PValueColumnName])) / i, 1)
    }
    # Method 2:
    # FilteredData[, AdjustedPValueColumnName] <- p.adjust(unlist(FilteredData[, PValueColumnName]), method = "fdr")
  }
  
  return(FilteredData)
}

convert_string_to_go_array <- function(string, pattern = "; ") {
  suppressPackageStartupMessages(library("stringr"))
  
  Array <- unlist(str_split(string, pattern))
  # Remove empty elements
  return(Array[nzchar(Array)])
}

# To generate the latest godir, See: https://bioconductor.org/packages/release/bioc/vignettes/GOfuncR/inst/doc/GOfuncR.html#conversion-from-.obo-format
# Python scripts to convert https://current.geneontology.org/ontology/go-basic.obo into a godir: https://github.com/sgrote/OboToTerm
get_unique_child_nodes_batch <- function(GOList, godir = "~/Desktop/RLibrary/godir-20240617") {
  suppressPackageStartupMessages(library("GOfuncR"))
  
  # A GO-ID itself is also considered as a child with a distance of 0
  ChildNodes <- get_child_nodes(GOList, godir = godir)
  ChildNodeIDs <- unique(ChildNodes$child_go_id)
  
  return(ChildNodeIDs)
}
